#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countApplesAndOranges function below.
def countApplesAndOranges(s, t, a, b, m, n, apples, oranges):
    i=0
    ap=0
    ora=0
    while i<m and i<n:
        if (a+apples[i])>=s and (a+apples[i])<=t:
            ap=ap+1
        if (b+oranges[i])>=s and (b+oranges[i])<=t:
            ora=ora+1
        i=i+1
    while i<m:
        if (a+apples[i])>=s and (a+apples[i])<=t:
            ap=ap+1
        i=i+1
    while i<n:
        if (b+oranges[i])>=s and (b+oranges[i])<=t:
            ora=ora+1
        i=i+1
    print(ap)
    print(ora)

if __name__ == '__main__':
    st = input().split()

    s = int(st[0])

    t = int(st[1])

    ab = input().split()

    a = int(ab[0])

    b = int(ab[1])

    mn = input().split()

    m = int(mn[0])

    n = int(mn[1])

    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, m, n, apples, oranges)
