#!/bin/python3

import os
import sys

#
# Complete the getTotalX function below.
#
def getTotalX(a, b):
    k=a[-1]
    c=0
    while(k<=b[0]):
        r=list(map(lambda x:k%x,a))
        r1=list(map(lambda x:x%k,b))
        if r.count(0)==len(a) and r1.count(0)==len(b):
            c=c+1
        k=k+a[-1]
    return(c)
if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    total = getTotalX(a, b)

    f.write(str(total) + '\n')

    f.close()
