#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
def plusMinus(arr):
    c=0
    c1=0
    c2=0
    for i in range(len(arr)):
        if arr[i]>0:
            c=c+1
        elif arr[i]==0:
            c1=c1+1
        else:
            c2=c2+1
    print("%.6f" % (c/len(arr)))
    print("%.6f" % (c2/len(arr)))
    print("%.6f" % (c1/len(arr)))

if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
