#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the repeatedString function below.
def repeatedString(s, n):
    if(s.count('a')==len(s)):
        return(n)
    else:
        na=s.count('a')
        k=n//len(s)
        t=na*k
        l=s[:n-(k*len(s))].count('a')
        t=t+l
        return(t)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    n = int(input())

    result = repeatedString(s, n)

    fptr.write(str(result) + '\n')

    fptr.close()
