#!/bin/python3

import os
import sys

#
# Complete the timeConversion function below.
#
def timeConversion(s):
    t=s.split(':')
    if t[2][-2:]=='AM':
        if s[:2]=='12':
            k='00'+s[2:-2]
            return(k)
        else:
            return(s[:-2])
    else:
        if s[:2]=='12':
            k='12'+s[2:-2]
        else:
            k=12+int(s[:2])
            k=str(k)+s[2:-2]
        return(k)

if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    f.write(result + '\n')

    f.close()
